// Create User
POST http://localhost:5000/users
Content-Type: application/json

{
    "first_name": "Ibnu",
    "last_name": "Fauzan Affifudin",
    "email": "fauzanibnu343@gmail.com",
    "password": "12345678",
    "confirmPassword": "12345678",
    "role": "admin"
}

###
// Create Admin
POST http://localhost:5000/register
Content-Type: application/json

{
   "first_name": "Ibnu",
    "last_name": "Fauzan Affifudin",
    "email": "fauzanibnu343@gmail.com",
    "password": "12345678",
    "confirmPassword": "12345678",
    "role": "admin"
}

###
//Login Admin
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "fauzanibnu343@gmail.com",
    "password": "12345678"
}

###
// Create user
POST http://localhost:5000/register
Content-Type: application/json

{
    "first_name": "Bronya",
    "last_name": "Zaychik",
    "email": "touchme0709@gmail.com",
    "password": "12345678",
    "confirmPassword": "12345678",
    "role": "user"
}

###
//Login user
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "touchme0709@gmail.com",
    "password": "12345678"
}


###
//Get User Login
GET http://localhost:5000/authusers

###
//logout
DELETE  http://localhost:5000/logout


###
// get All User
GET http://localhost:5000/users

###
// get User by ID
GET http://localhost:5000/users/73b2a651-9e01-4552-a714-84c67ef15e1d

###
// update User by ID
PATCH  http://localhost:5000/users/2d5b1947-e0a0-41a2-8a7f-594d59a9373e
Content-Type: application/json

{
    "first_name": "Bronya",
    "last_name": "Zaychik Updated 2",
    "email": "bunnycute321@gmail.com",
    "password": "",
    "confirmPassword": "",
    "role": "user"
}

###
// Delete User by ID
DELETE   http://localhost:5000/users/2d5b1947-e0a0-41a2-8a7f-594d59a9373e


//PRODUCTS
###
// Create Products
POST http://localhost:5000/products
Content-Type: application/json

{
    "name": "Laptop coba 4",
    "description": "Intel Collab, RAM 16GB",
    "category": "gaming",
    "price": "1500000",
    "stock": "15",
    "image": "qqq"
}

###
// get All Product
GET http://localhost:5000/products

###
// get Product by ID
GET http://localhost:5000/products/c380ed6c-4897-46ea-9be9-6ebfd7591387

###
// get Update Product
PATCH  http://localhost:5000/products/4b80df7a-5ad4-431b-bdf4-843fcfc7d040
Content-Type: application/json

{
    "name": "Asus ROG",
    "description": "Intel I7, RAM 16GB",
    "price": "2000000",
    "stock": "5",
    "image": "eeee"
}

###
// Delete product by ID
DELETE   http://localhost:5000/products/769dfe6e-8e77-4449-9eb4-d12dccdec7f4


###
// Create Feedbacks
POST http://localhost:5000/feedbacks
Content-Type: application/json

{
    "feedback": "UI user bisa dibagusin lagi",
    "rate": "4"
}

###
// get All Feedbacks
GET http://localhost:5000/feedbacks

###
// get All Feedbacks
GET http://localhost:5000/feedbacks/4cdc80a4-0a6c-4611-9c70-24a3257dfade

###
// get Update Feedbacks
PATCH http://localhost:5000/feedbacks/67b5f976-58ec-498f-9836-9835f9b52f0c
Content-Type: application/json

{
    "feedback": "UI user bisa dibagusin lagi 123",
    "rate": "4"
}

###
// Delete feedback by ID
DELETE   http://localhost:5000/feedbacks/67b5f976-58ec-498f-9836-9835f9b52f0c



//CART

### 
//Create Cart
POST http://localhost:5000/createcart
Content-Type: application/json

{
    "userUuid": "3384f64f-db77-48a1-9a75-c0235543fd4f",
    "productId": "b67ca7d5-e77c-448c-b1bf-08866c5db8ea",
    "quantity": "7"
}

###
// get All Cart
GET http://localhost:5000/keranjang

###
// get All Cart
GET http://localhost:5000/cart/9993decf-94c3-486c-9ff2-67fd37dbc77b

### Update Cart
PATCH http://localhost:5000/cart/9993decf-94c3-486c-9ff2-67fd37dbc77b
Content-Type: application/json

{
    "quantity": "77"
}

// Delete feedback by ID
###
DELETE   http://localhost:5000/cart/caa9de99-0d71-46bf-ba9e-675528c6a9c5
