//CART ITEM

###
// get All CartItem
GET http://localhost:5000/cartItem

###
// get All CartItem by Id
GET http://localhost:5000/cartItem/1b5faa8a-1bfa-48af-81a9-5b57f81c6d27

### 
//Create CartItem
POST http://localhost:5000/cartItem
Content-Type: application/json

{
    "productId": "193e3d4c-a809-4676-a70f-47f20e7ee3be",
    "cartId": "04b145f9-797a-4dea-a2c4-061d9b4f0075"
}


### Update CartItem
PATCH http://localhost:5000/cartItem/e37645bf-77c0-4bd0-aa39-59fe7ab63bd5
Content-Type: application/json

{
    // "cartId": "54245a7f-aeba-4e5c-974c-76b7778b1559",
    "productId": "a4df3c8b-b355-41be-8373-20bb73f25c82"
}

// Delete CartItem by ID
###
DELETE   http://localhost:5000/cartItem/caa9de99-0d71-46bf-ba9e-675528c6a9c5